--
-- 由SQLiteStudio v3.2.1 产生的文件 周二 5月 7 17:52:28 2019
--
-- 文本编码：System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- 表：attach
CREATE TABLE "attach" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"name" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"md5" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"size" INTEGER  NULL DEFAULT NULL ,"local_ctime" TIMESTAMP  NULL DEFAULT NULL ,"local_mtime" TIMESTAMP  NULL DEFAULT NULL ,"remark" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"modified_time" TIMESTAMP  NOT NULL  ,"created_time" DATETIME  NULL DEFAULT NULL ,"yn" SMALLINT  NULL DEFAULT NULL );

-- 表：comment
CREATE TABLE "comment" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"username" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"email" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"url" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"content" TEXT  NULL  COLLATE BINARY,"post_id" INTEGER  NULL DEFAULT NULL ,"parent_id" INTEGER  NULL DEFAULT NULL ,"parent_type" SMALLINT  NULL DEFAULT NULL ,"ip" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"user_agent" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"remark" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"modified_time" TIMESTAMP  NOT NULL  ,"created_time" DATETIME  NULL DEFAULT NULL ,"yn" SMALLINT  NULL DEFAULT NULL );

-- 表：dict
CREATE TABLE "dict" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"dict_type" SMALLINT  NULL DEFAULT NULL ,"dict_key" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"dict_value" TEXT  NULL  COLLATE BINARY,"remark" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"modified_time" TIMESTAMP  NOT NULL  ,"created_time" DATETIME  NULL DEFAULT NULL ,"yn" SMALLINT  NULL DEFAULT NULL );

-- 表：post
CREATE TABLE "post" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"title" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"username" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"content" TEXT  NULL  COLLATE BINARY,"post_type" SMALLINT  NULL DEFAULT NULL ,"status" SMALLINT  NULL DEFAULT NULL ,"remark" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"modified_time" TIMESTAMP  NOT NULL  ,"created_time" DATETIME  NULL DEFAULT NULL ,"yn" SMALLINT  NULL DEFAULT NULL );

-- 表：relation
CREATE TABLE "relation" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"type" SMALLINT  NULL DEFAULT NULL ,"parent_id" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"child_id" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"remark" VARCHAR(255)  NULL DEFAULT NULL COLLATE BINARY,"modified_time" TIMESTAMP  NOT NULL  ,"created_time" DATETIME  NULL DEFAULT NULL ,"yn" SMALLINT  NULL DEFAULT NULL );

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
